class Item(cost , png):
    def __init__(self, cost, png):
        self.cost = cost
        self.picture = png

IRingOfBasilius = Item(425, "./icons/items/basilius.png")
IBladesOfAttack = Item(450, "./icons/items/blades.png")
IBlightStone = Item(300, "./icons/items/blight.png")
IBootsOfSpeed = Item(500, "./icons/items/boots.png")
IBracer = Item(505, "./icons/items/bracer.png")
IBuckler = Item(425, "./icons/items/buckler.png")
ICirclet = Item(155, "./icons/items/circlet.png")
IClarity = Item(50, "./icons/items/clarity.png")
ICrown = Item(450, "./icons/items/crown.png")
IDustOfAppearance = Item(50, "./icons/items/dusts.png")
IFaerieFire = Item(65, "./icons/items/faerie.png")
IFluffyHat = Item(250, "./icons/items/fluffy.png")
IGauntletsOfStrength = Item(140, "./icons/items/gauntlets.png")
IIronBranch = Item(50, "./icons/items/gg.png")
IGlovesOfHaste = Item(450, "./icons/items/gloves.png")
IHeaddress = Item(425, "./icons/items/headdress.png")
IMango = Item(65, "./icons/items/mango.png")
IMantleOfIntelligence = Item(140, "./icons/items/mantle.png")
INullTalisman = Item(505, "./icons/items/nullik.png")
IObserverWard = Item(0, "./icons/items/obs.png")
IRingOfProtection = Item(175, "./icons/items/protection.png")
IQuellingBlade = Item(100, "./icons/items/quelling.png")
IRingOfRegen = Item(175, "./icons/items/regen.png")
ISagesMask = Item(175, "./icons/items/sage's.png")
ISentryWard = Item(50, "./icons/items/sentry.png")
ISlippersOfAgility = Item(140, "./icons/items/slippers.png")
ISmokeOfDeceit = Item(50, "./icons/items/smoke.png")
IMagickStick = Item(200, "./icons/items/stick.png")
ITango = Item(90, "./icons/items/tango.png")
IOrbOfVenom = Item(250, "./icons/items/venom.png")
IMagickWand = Item(450, "./icons/items/wand.png")